# Generated by Django 4.2.7 on 2024-02-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_serializer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
