# Generated by Django 4.2.7 on 2024-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_serializer_app', '0003_alter_account_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='deepak c.', editable=False, max_length=100),
        ),
    ]
