# Generated by Django 4.2.7 on 2024-02-02 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_app', '0003_alter_comment_created_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 10, 37, 58, 808893, tzinfo=datetime.timezone.utc)),
        ),
    ]
