# Generated by Django 4.2.7 on 2024-02-05 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_app', '0006_alter_comment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 5, 18, 26, 846338)),
        ),
    ]
