# Generated by Django 4.2.7 on 2024-02-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_app', '0007_alter_comment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
